architecture: "replication"
auth: 
  rootPassword: my-secret-pwd
  database: my-db
  username: my-user
  password: my-pass
primary:
  persistence:
    storageClass: gp2
secondary:
  replicaCount: 2
  persistence:
    storageClass: gp2